export function pfnTask04_4() {
  return [
    { color: "red", text: ">>> " },
    { color: "black", text: "status = " },
    { color: "orange", text: "True" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "black", text: "two = 2" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "purple", text: "print" },
    { color: "black", text: "(" },
    { color: "black", text: "status" },
    { color: "black", text: ")" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "red", text: "???" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "purple", text: "print" },
    { color: "black", text: "(" },
    { color: "black", text: "two" },
    { color: "black", text: ")" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "red", text: "???" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "purple", text: "print" },
    { color: "black", text: "(" },
    { color: "orange", text: "False" },
    { color: "black", text: ")" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "red", text: "???" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "purple", text: "print" },
    { color: "black", text: "(" },
    { color: "green", text: "\"There are\"" },
    { color: "black", text: ",two," },
    { color: "green", text: "\"boolean values which are\"" },
    { color: "black", text: ",status," },
    { color: "green", text: "\"and\"" },
    { color: "black", text: "," },
    { color: "orange", text: "False" },
    { color: "black", text: ")" },
    { color: "blue", text: "\n" },
    { color: "red", text: ">>> " },
    { color: "red", text: "???" },
  ];
}